export const IPC_CHANNELS = {
  updates: {
    preferences: "updates:preferences",
    setEnabled: "updates:set-enabled",
    status: "updates:status",
    statusChanged: "updates:status-changed",
    releaseNotes: "updates:release-notes",
    restartAndInstall: "updates:restart-and-install",
  },
  backend: {
    status: "backend:status",
    statusChanged: "backend:status-changed",
    restartServer: "backend:restart-server",
    getRuntimeStatus: "backend:get-runtime-status",
    setImageModel: "backend:set-image-model",
    setExecutionProvider: "backend:set-execution-provider",
    listLibraries: "backend:list-libraries",
    createLibrary: "backend:create-library",
    updateLibrary: "backend:update-library",
    deleteLibrary: "backend:delete-library",
    assetMetadata: "backend:asset-metadata",
    listAssets: "backend:list-assets",
    listFolders: "backend:list-folders",
    countAssets: "backend:count-assets",
    catalogRevision: "backend:catalog-revision",
    getTextEmbeddingCoverage: "backend:get-text-embedding-coverage",
    getImageEmbeddingCoverage: "backend:get-image-embedding-coverage",
    getOcrModels: "backend:get-ocr-models",
    getSearchModels: "backend:get-search-models",
    search: "backend:search",
    cancelSearch: "backend:cancel-search",
    startJob: "backend:start-job",
    listJobs: "backend:list-jobs",
    cancelJob: "backend:cancel-job",
    subscribeJob: "backend:subscribe-job",
    unsubscribeJob: "backend:unsubscribe-job",
    jobSnapshot: "backend:job-snapshot",
    jobConnection: "backend:job-connection",
    ensureThumbnails: "backend:ensure-thumbnails",
  },
  native: {
    appInfo: "native:app-info",
    collectDiagnostics: "native:collect-diagnostics",
    recentBackendLog: "native:recent-backend-log",
    openExternalUrl: "native:open-external-url",
    openLicenseInformation: "native:open-license-information",
    chooseDirectory: "native:choose-directory",
    chooseVisualSearchImage: "native:choose-visual-search-image",
    addToVisualSearch: "native:add-to-visual-search",
    showFileContextMenu: "native:show-file-context-menu",
    prepareFileDrag: "native:prepare-file-drag",
    startFileDrag: "native:start-file-drag",
  },
} as const;
